name: Java Maven CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          # 0 indicates all history for all branches and tags
          fetch-depth: "0"
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: git status
      run: |
        git status
        git remote -v

    - name: check release tag
      if: github.event_name == 'pull_request'
      run: scripts/check-release.sh

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: tag release
      if: github.event_name == 'push'
      run: scripts/tag-release.sh

